includes:
  - base.yaml
model:
  model_name: SG_GIN
ood:
  ood_alg: SGN
  ood_param: 1e-5
train:
  max_epoch: 300
#  tr_ctn: True
#  ctn_epoch: 140
  lr: 1e-3
  stage_stones: [100, 150]
  weight_decay: 0.
  mile_stones: [150]
#random_seed: 2341