name: pygood
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - torchvision==0.11.2
  - cudatoolkit=11.3
  - torchaudio==0.10.1
  - pytorch==1.10.1
  - rdkit>=2020.09.5
  - pynvml=11.4
  - pip>=21.0
  - pip:
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torch-geometric==2.0.4
    - setuptools==59.5.0
    - cilog==1.2.3
    - gdown>=4.4.0
    - matplotlib==3.5.2
    - munch==2.5.0
    - networkx==2.8
    - ogb>=1.3.4
    - pytest==7.1.2
    - ruamel.yaml==0.17.21
    - protobuf==3.20.1
    - sphinx>=4.5
    - sphinx-rtd-theme==1.0.0
    - tensorboard==2.8.0
    - tqdm==4.64.0
    - typed-argument-parser==1.7.2
    - dive-into-graphs
    - cvxopt>=1.3.0
    - pynvml>=11.4.1
    - psutil>=5.9.1
