includes:
  - base.yaml
model:
  model_name: EERMGCN
ood:
  ood_alg: EERM
  ood_param: 1.
  extra_param:
    - 10   # K: Number of context generator
    - 1   # T
    - 2   # Number of sample
    - 5e-3    # Learning rate for REINFORCE
train:
  max_epoch: 200
  lr: 5e-3
  mile_stones: [200]