includes:
  - base.yaml
model:
  model_name: DANN_vGIN
ood:
  ood_alg: DANN
  ood_param: 0.1
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
