includes:
  - base.yaml
model:
  model_name: GEIGIN
ood:
  ood_alg: GEI
  ood_param: 0.0
  extra_param:
    - 1
    - 0
    - 20
    - 50
    - 0
    - true
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
  pre_train: 100
  weight_decay: 0.0
log_file: exp_0
clean_save: true
