includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.8
  extra_param:
    - 10.0
train:
  max_epoch: 200
  lr: 0.001
  weight_decay: 0.0
log_file: exp_0
clean_save: true
