includes:
  - ../base.yaml
  - ../../GOODCMNIST.yaml
extra_param:
  -     # LA
    - 100
    - 10
    - 1
  -      # EC
    - 0
  -      # EA
    - 10
    - 1
    - 0.1
  -       # r decay interval
    - 10
  -       # EF
    - 1
    - 0.1
  -
    - true