includes:
  - base.yaml
model:
  model_name: GEIvGIN
ood:
  ood_alg: GEI
  ood_param: 0.0
  extra_param:
    - 100
    - 0
    - 1
    - 10
    - 1
    - true
train:
  max_epoch: 200
  lr: 0.001
  pre_train: 50
  mile_stones:
    - 300
  train_bs: 64
  val_bs: 128
  test_bs: 128
  weight_decay: 0.0
log_file: exp_0
clean_save: true
