includes:
  - base.yaml
model:
  model_name: vGIN
ood:
  ood_alg: GroupDRO
  ood_param: 0.1
train:
  max_epoch: 500
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
