includes:
  - base.yaml
model:
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.8     # causal ratio
  extra_param:
    - 1     # additional loss control
train:
  max_epoch: 200
  train_bs: 32
  lr: 1e-3


